### ISSUE TITLE
一直有错误信息

### ISSUE THREAD

**Issue by kylinfedora** [nesror/xiaomi_miio_toilet#3]
![image](https://user-images.githubusercontent.com/2525979/151537407-93143c9c-848e-4aea-8a2e-e54971890432.png)

Update state error.
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_miio_toilet/binary_sensor.py", line 107, in async_update
    "status_seatheat": seatTemp[1] == 1,
IndexError: list index out of range

**Comment by jyz0501** [comment]
2023-11-08 22:00:49.634 ERROR (MainThread) [custom_components.xiaomi_miio_toilet.binary_sensor] Update state error.
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_miio_toilet/binary_sensor.py", line 111, in async_update
    "status_seatheat": seatTemp[1] == 1,
                       ~~~~~~~~^^^
IndexError: list index out of range
